### ISSUE TITLE
DMR Help!

### ISSUE THREAD

**Issue by alwinhb** [travisgoodspeed/myk82rom#1]
@travisgoodspeed I was unable to open the issue for - https://github.com/travisgoodspeed/md380tools

I am working on implementing DMR on a custom hardware. I needed to understand if this code can help - https://github.com/travisgoodspeed/md380tools Also does it contains DMR complete implementation tier1/2/3

**Comment by alwinhb** [comment]
@travisgoodspeed Can you guide on the above please, Whether the code contains DMR protocol as well?

**Comment by travisgoodspeed** [comment]
This repository is about a cryptography chip from the mid nineties.  It's my hobby, and I don't want my recreation ruined by support requests in the issue tracker for a radio project that stopped being fun years ago.

Please understand that and stop filing these tickets in my issue trackers.
